sonar.projectKey=meghashree-hu_ZeroTrace
sonar.organization=meghashree-hu

sonar.projectName=ZeroTrace

sonar.sources=backend/src,frontend/src

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.test.*,**/*.spec.*

sonar.javascript.lcov.reportPaths=coverage/lcov.info